AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for WebServer with Security Group and EC2 Instance

Parameters:

  FileSystemResource: 
    Type: String

  DatabaseHostname:
    Type: String

  DatabaseRootUser:
    Type: String

  DatabaseRootPassword:
    Type: String
    NoEcho: True

  WordpressDatabase:
    Type: String

  WordpressDatabaseUser:
    Type: String

  WordpressDatabasePassword:
    Type: String
    NoEcho: True

  WordpressHostname:
    Type: String

  AppSecurityGroup:
    Type: String

  LoadBalancerSecurityGroup:
    Type: String

  VpcId:
    Type: String

  LatestAmiId:
    Description: The latest Amazon Linux 2023 AMI from the Parameter Store
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.medium
    ConstraintDescription: must be a valid EC2 instance type.

  SubnetA:
    Type: AWS::EC2::Subnet::Id
    Description: First subnet for ALB
  
  SubnetB:
    Type: AWS::EC2::Subnet::Id
    Description: Second subnet for ALB (must be in different AZ)

  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id

Resources:
# DNS
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref WordpressHostname
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt ElasticLoadBalancer.CanonicalHostedZoneID
        DNSName: !GetAtt ElasticLoadBalancer.DNSName

  SSLCert:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Ref WordpressHostname
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref WordpressHostname
          HostedZoneId: !Ref HostedZoneId
# App
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier: 
        - !Ref SubnetA
        - !Ref SubnetB
      TargetGroupARNs:
        - !GetAtt TargetGroup80.TargetGroupArn
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 2
    CreationPolicy:
      ResourceSignal:
        Count: 2  
        Timeout: PT15M

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-LaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Name: !Ref InstanceProfile
        SecurityGroupIds:
          - !Ref AppSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            dnf update -y
            dnf install -y amazon-efs-utils docker mariadb1011-client-utils

            mysql -h${DatabaseHostname} -u${DatabaseRootUser} -p${DatabaseRootPassword} <<EOF
            CREATE DATABASE IF NOT EXISTS ${WordpressDatabase};
            CREATE USER IF NOT EXISTS '${WordpressDatabaseUser}'@'%' IDENTIFIED BY '${WordpressDatabasePassword}';
            GRANT ALL PRIVILEGES ON ${WordpressDatabase}.* TO '${WordpressDatabaseUser}'@'%';
            FLUSH PRIVILEGES;
            EOF

            useradd -m -u 1100 wordpress
            usermod -aG docker wordpress
            su wordpress -c 'mkdir -p /home/wordpress/{wp-data,data_backups}'
            echo "${FileSystemResource}:/ /home/wordpress/wp-data efs _netdev,tls,iam 0 0" >> /etc/fstab
            mount -a
            systemctl enable --now docker
            su wordpress -c bash <<'EOF'
            docker run -d \
              --name wordpress \
              --restart always \
              -v "/home/wordpress/wp-data:/var/www/html" \
              -v "/home/wordpress/data_backups:/var/tmp/backups" \
              -p 80:80 \
              -e WORDPRESS_CONFIG_EXTRA="define( 'WP_HOME', \"https://${WordpressHostname}\" ); define( 'WP_SITEURL', \"https://${WordpressHostname}\");" \
              -e WORDPRESS_DB_HOST=${DatabaseHostname} \
              -e WORDPRESS_DB_USER=${WordpressDatabaseUser} \
              -e WORDPRESS_DB_PASSWORD=${WordpressDatabasePassword} \
              -e WORDPRESS_DB_NAME=${WordpressDatabase} \
              wordpress:6.9.0-apache
            EOF
            # Signal success or failure
            /opt/aws/bin/cfn-signal -e $? \
              --stack ${AWS::StackName} \
              --resource AutoScalingGroup \
              --region ${AWS::Region}

  ElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Type: application

  TargetGroup80:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        Name: !Sub ${AWS::StackName}-tg80
        Protocol: HTTP
        Port: 80
        TargetType: instance
        VpcId: !Ref VpcId

  LoadBalancerListener80:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: redirect
        RedirectConfig:
          Protocol: "HTTPS"
          Port: 443
          Host: "#{host}"
          Path: "/#{path}"
          Query: "#{query}"
          StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref ElasticLoadBalancer
      Port: 80
      Protocol: HTTP

  LoadBalancerListener443:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      LoadBalancerArn: !Ref ElasticLoadBalancer
      Protocol: HTTPS
      Port: 443
      SslPolicy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
      Certificates: 
        - CertificateArn: !Ref SSLCert
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup80

# Roles for EC2
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref InstanceRole

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: 'Allow'
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref InstancePolicy

  InstancePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'ssm:*'
              - 'ssmmessages:*'
              - 'ec2messages:*'
            Resource: "*"

Outputs:
  WordpressUrl:
    Value: !Join
      - ''
      - - https://
        - !Ref WordpressHostname
  StackName:
    Value: !Ref AWS::StackName
